project:
  type: website
  output-dir: docs
  resources:
    - subscribe.html

website:
  title: "Nick Mesmer Blog"
  margin-header: subscribe.html
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/nicholas-mesmer
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



